# Generated by Django 5.0.6 on 2024-06-25 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(choices=[('Time Series', 'Time Series'), ('Heat Map', 'Heat Map'), ('Data Download', 'Data Download')], max_length=15)),
                ('startDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('temporalLevel', models.CharField(choices=[('hourly', 'hourly'), ('daily', 'daily'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=10)),
                ('aggLevel', models.CharField(choices=[('min', 'min'), ('max', 'max'), ('mean', 'mean')], max_length=10)),
                ('north', models.DecimalField(decimal_places=35, max_digits=40)),
                ('east', models.DecimalField(decimal_places=35, max_digits=40)),
                ('south', models.DecimalField(decimal_places=35, max_digits=40)),
                ('west', models.DecimalField(decimal_places=35, max_digits=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
