# Generated by Django 5.0.6 on 2024-06-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='aggLevel',
        ),
        migrations.RemoveField(
            model_name='query',
            name='east',
        ),
        migrations.RemoveField(
            model_name='query',
            name='endDateTime',
        ),
        migrations.RemoveField(
            model_name='query',
            name='north',
        ),
        migrations.RemoveField(
            model_name='query',
            name='requestType',
        ),
        migrations.RemoveField(
            model_name='query',
            name='south',
        ),
        migrations.RemoveField(
            model_name='query',
            name='startDateTime',
        ),
        migrations.RemoveField(
            model_name='query',
            name='temporalLevel',
        ),
        migrations.RemoveField(
            model_name='query',
            name='west',
        ),
    ]
