# Generated by Django 5.0.6 on 2024-08-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_query_trajectoriesuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='requestType',
            field=models.CharField(choices=[('Summarize', 'Summarize'), ('Impute', 'Impute'), ('Generate', 'Generate'), ('Download', 'Download')], max_length=15),
        ),
    ]
