# Generated by Django 5.0.6 on 2024-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_query_requesttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='operation',
            field=models.CharField(choices=[('Trajectory Classification', 'Trajectory Classification'), ('Trajectory Generation', 'Trajectory Generation'), ('Trajectory Imputation', 'Trajectory Imputation'), ('Trajectory Summarization', 'Trajectory Summarization')], default='bla', max_length=30),
            preserve_default=False,
        ),
    ]
